"""empty message

Revision ID: 67df944958b5
Revises: 83177b1a287a
Create Date: 2020-01-23 11:38:06.307594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67df944958b5'
down_revision = '83177b1a287a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=500), nullable=True))
    op.execute('''
      UPDATE artist
      SET website = ''
      WHERE website IS NULL;
    ''')
    op.execute('''
      UPDATE venue
      SET website = ''
      WHERE website IS NULL;
    ''')
    op.alter_column('artist', 'website', nullable=False)
    op.alter_column('venue', 'website', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
